### PR TITLE
version: 1.21.11

### LINKED ISSUE #7382: [BUG] Item Chams causes Flickering
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

35.2

### Operating System

Windows 11

### Minecraft Version

21.8

### Describe the bug

Turning Item Chams on on any setting causes the whole screen to flicker
Otherwise the Module works fine
This is on an AMD integrated GPU

### Steps to reproduce

- Launch LiquidBounce
- Go into SinglePlayer World
- Turn on Item Chams

### Client Log

```shell
[23:51:22] [nioEventLoopGroup-3-1/INFO]: [id: 0x9613fc11, L:/[0:0:0:0:0:0:0:0]:63480] READ: [id: 0xab3a2c09, L:/127.0.0.1:63480 - R:/127.0.0.1:63557]
[23:51:22] [nioEventLoopGroup-3-1/INFO]: [id: 0x9613fc11, L:/[0:0:0:0:0:0:0:0]:63480] READ COMPLETE
[26188:26796:1211/235122.691:ERROR:cef\libcef\browser\native\menu_runner_views_aura.cc:25] Window handle is required for default OSR context menu.
[26188:26796:1211/235122.691:ERROR:cef\libcef\browser\menu_manager.cc:223] Default context menu implementation is not available; canceling the menu
[26188:2588:1211/235134.725:ERROR:google_apis\gcm\engine\registration_request.cc:291] Registration response error message: DEPRECATED_ENDPOINT
[23:51:39] [nioEventLoopGroup-3-1/INFO]: [id: 0x9613fc11, L:/[0:0:0:0:0:0:0:0]:63480] READ: [id: 0xc3ef8df7, L:/127.0.0.1:63480 - R:/127.0.0.1:63566]
[23:51:39] [nioEventLoopGroup-3-1/INFO]: [id: 0x9613fc11, L:/[0:0:0:0:0:0:0:0]:63480] READ COMPLETE
```

### Screenshots

Image

### PR DESCRIPTION
**Pull request by DataM0del**
fixes #7382

Skipped features:
- BetterChat.Copy
- Chams

Known issues:
- Backtrack.Render.Model incorrect light & position (maybe also outline)
- Combat and other features don't support spear and other customized items with different ranges (from component).
- Spear should have its own item comparator for enchantments in category

current todos:
- [x] Main Menu (on the first time it shows? assuming it's not an issue with this port) is broken, it only shows a background (see below). MCEF issue? idk
- [x] DrawContext.drawBorder is renamed or gone
- [x] stride distance is also gone, probably into some render state thing
- [x] MixinEntityRenderDispatcher Hitbox module broken
- [x] `vertexConsumers` is gone, MixinEntityRenderer.java line 98
- [x] `renderBakedItemQuads` might not be the right method to hook (MixinItemRenderer line 39)
- [x] `injectTrueSight` is broken in LivingEntityRenderer
- [x] `CustomAmbience` layers is broken since I need to look into mc diffs again // This feature is removed.
- [ ] chams rendering needs to be moved from WorldRenderer to somewhere else
- [x] `onRenderGlow` needs to be fixed in WorldRenderer
- [x] the draw outline in WorldRenderer is not hooked since idk what to do lol
- [x] `renderSetupTerrainModifyArg` needs to be fixed in WorldRenderer
- [x] depth parameter is gone in every ElementRenderState record thing (check setupVertices)
- [x] `accountType` is removed and now replaced with `mc.isOfflineDeveloperMode` in most(?) cases (SessionSerializer)
- [x] `apiServices` is a record and you can't reassign the sessionService because of that
- [ ] `ModuleBacktrack`'s model renderer looks to be at incorrect position
- [x] StorageESP & BlockESP glow mode
- [x] StorageESP Glow looks unapplied to entities like Donkey with chest
- [x] BlockOutline line 109 is probably correct since it shouldn't render when the camera isn't available
- [x] ProtectionZones also is the same as BlockOutline (line 245)
- [x] also ModuleAirPlace line 87
- [x] `SkinTextures` got a huge refactor, so it uses `.body.texturePath()` instead of `.texture` thing
- [x] `ModulePacketMine` line 350, idk if `mc.submit` is correct, it probably isn't (but PacketMine works, so it's probably correct)
- [x] `TextureFunctions.kt` line 82, converted `texture` to `body` when using the skin thing
- [x] `RenderShortcuts.kt` line 187, idk if an empty model offset is correct
- [x] `WorldToScreen.kt` line 81, viewport{Width,Height} got removed, replaced with texture{Width,Height}
- [x] `MixinEntryListWidget.java` line 38, they removed the boolean for if it should render the entry list or not, so we assume it should by default when world is not null (`WrapWithCondition` and return `HideAppearance.INSTANCE.isHidingNow()`)
- [x] MixinClientPlayerEntity antihunger(sprint)
- [ ] MixinChatHud ModuleBetterChat Copy feature broken
- [x] FreeCam doesn't show player self if first perspective
- [x] MixinGameRenderer `findCrosshairTarget` gone, moved to `ClientPlayerEntity.getCrosshairTarget`

### CODE REVIEW

**Comment by DataM0del** [comment]
image
awesome so item renderer is broken aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by DataM0del** [comment]
ok well the item renderer technically works as usual but if you get new items that haven't been rendered yet it'll just appear as air

**Comment by DataM0del** [comment]
going to ignore it at this point and just work on other stuff

**Comment by DataM0del** [comment]
image
ok fabric

**Comment by DataM0del** [comment]
image
(fixed, it renders the terrain too now)

**Comment by DataM0del** [comment]
image
still not fixed, let me check if the item renderer is fixed on the latest nightly build.
might be the scissoring lol

**Comment by DataM0del** [comment]
item renderer is still not fixed on the latest nightly build.

**Comment by DataM0del** [comment]
image
semicolon in Kotlin code :money_mouth_face:

**Comment by MukjepScarlet** [comment]
Might be helpful
https://docs.neoforged.net/primer/docs/1.21.9/

**Comment by DataM0del** [comment]
image
lol

File: src/main/kotlin/net/ccbluex/liquidbounce/features/itemgroup/groups/HeadsItemGroup.kt [hunk 1]
```diff
@@ -58,13 +56,7 @@ data class Head(val name: String, val uuid: UUID, val value: String) {
...
         builder.add(
             DataComponentTypes.PROFILE,
-            ProfileComponent(
-                Optional.empty(),
-                Optional.empty(),
-                PropertyMap().apply {
-                    put("textures", Property("textures", value))
-                }
-            )
+            ProfileComponent.ofDynamic(uuid)
```
Comment (MukjepScarlet) [inline src/main/kotlin/net/ccbluex/liquidbounce/features/itemgroup/groups/HeadsItemGroup.kt]: Does this work?

Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/features/itemgroup/groups/HeadsItemGroup.kt]: Not.

**Comment by VillainsRule** [comment]
i dont know what an ItemImageAtlas is but it seems like an opp ngl

**Comment by DataM0del** [comment]
> i dont know what an ItemImageAtlas is but it seems like an opp ngl

it renders items so e.g. the client HUD can use it.

**Comment by MukjepScarlet** [comment]
First version on 1.21.8 will be released in this weekend. You can take a rest about this...

**Comment by MukjepScarlet** [comment]
- [x] Fullbright gamma mode broken
- [ ] BlockESP/StorageESP glow (outline works)

**Comment by MukjepScarlet** [comment]
All `SkinTextures` usages are likely fixed?

**Comment by MukjepScarlet** [comment]
@DataM0del 1.21.11 now. Do you want to skip 1.21.10?

**Comment by MukjepScarlet** [comment]
1.21.11 launched. But VFP is still 1.21.10

**Comment by VillainsRule** [comment]
did 1.21.11 change too much rendering? idk

VFP will probably update within the coming days

**Comment by MukjepScarlet** [comment]
Not so much. Less than 100 Kotlin compiler issues. (At least it compiles successfully now)

**Comment by MukjepScarlet** [comment]
I'd like to skip 1.21.10 because we something changes again (in this PR),and we can join 1.21.10 servers with 1.21.8 client.

**Comment by MukjepScarlet** [comment]
I will push 1.21.11 update after VFP release.

**Comment by MukjepScarlet** [comment]
It depends on your opinion @DataM0del , I'm ready to launch

**Comment by 6x67** [comment]
@MukjepScarlet you can skip
image

sorry for forgetting about this for a while, I just didn't think about this because of me losing access to everything except my main discord account and the other ones which I had in a server with their credentials.

**Comment by MukjepScarlet** [comment]
Please update your TODO list.

**Comment by 6x67** [comment]
I can't because I don't have access to that account anymore...

**Comment by MukjepScarlet** [comment]
@1zun4 merge this

**Review by 1zun4 — APPROVED** [review]
