### PR TITLE
feat/fix(Sprint): fit 1.21.11 new component

### LINKED ISSUE #7449: Sprint not legal

### PR DESCRIPTION
**Pull request by MukjepScarlet**
The `UseEffects` component allows to control if player should stop sprinting on using the item.

closes #7449

### CODE REVIEW

File: src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleSprint.kt [hunk 1]
```diff
@@ -89,7 +91,7 @@ object ModuleSprint : ClientModule("Sprint", Category.MOVEMENT) {
     }
 
     @Suppress("unused")
-    private val sprintPreventionHandler = handler<SprintEvent> { event ->
+    private val sprintPreventionHandler = handler<SprintEvent>(priority = FINAL_DECISION) { event ->
```
Comment (1zun4) [inline src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleSprint.kt]: Do not make [Sprint] module act as FINAL_DECISION. This will overwrite other modules!

**Review by 1zun4 — CHANGES_REQUESTED** [review]

File: src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleSprint.kt (hunk 1 above)
Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleSprint.kt]: Done

Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleSprint.kt]: Please compare the behavior with: 1.8 vanilla, 1.21.11 vanilla, 1.21.4 vanilla

**Review by 1zun4 — APPROVED** [review]
