### PR TITLE
fix: ArmorStatus in hotbar has gone out of bounds

### LINKED ISSUE #5839: [BUG] ArmorStatus in Hotbar has gone out of bounds
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Linux

### Minecraft Version

latest

### Describe the bug

ArmorStatus in Hotbar has out of bounds

### Steps to reproduce

idk

### Client Log

```shell
unimportant
```

### Screenshots

Image

### PR DESCRIPTION
**Pull request by sqlerrorthing**
closes #5839

### CODE REVIEW

File: src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/protocol/rest/v1/game/PlayerFunctions.kt [hunk 1]
```diff
@@ -106,7 +106,7 @@ data class PlayerData(
             player.getActualHealth().fixNaN(),
             player.maxHealth.fixNaN(),
             player.absorptionAmount.fixNaN(),
-            player.armor,
+            player.armor.coerceAtMost(20),
```
Comment (sqlerrorthing) [inline src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/protocol/rest/v1/game/PlayerFunctions.kt:109]: because the max value in the hotbar status - 20.

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src-theme/src/routes/hud/elements/hotbar/HotBar.svelte#L83-L89
