### PR TITLE
version: 1.21.5

### LINKED ISSUE #5145: [BUG] MiniMap has wrong color of chunk edges
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nightly 0.22.1

### Operating System

macOS, Linux, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 11

### Minecraft Version

1.21.4

### Describe the bug

image

### Steps to reproduce

toggle it on

### Client Log

```shell
no exceptions in log
```

### Screenshots

image

(test)
image

### PR DESCRIPTION
**Pull request by MukjepScarlet**
closes https://github.com/CCBlueX/LiquidBounce/issues/5145

TODO:
- [x] Outlines: ESP (removed), ItemESP (removed), BlockESP (fixed)
- [x] Glows: ESP, ItemESP, BlockESP, StorageESP
- [x] Sprint
- [x] Hitbox (testing needed)
- [x] SwordBlock broken. Should migrate to 1.21.5+ vanilla animations
- [x] Animations module. It doesn't change 1.21.5+ vanilla sword blocking. (designed or not?) And our "1.7" animation is different to 1.21.5 vanilla animation.
- [x] Text color is gone for scoreboard
- [x] Item name hotbar highlight not displaying text 
- [x] Blur broken on MacOS (arm64), making all HUD (browser + inbuilt) hidden
- [x] Accelerated Paint no longer works Windows

### CODE REVIEW

**Comment by MukjepScarlet** [comment]
@superblaubeere27 The render code needs rewrite. I don't understand OpenGL nor the new Minecraft "rendering engine", so if you are interested, then you can complete it. And... as you know the 2D rendering will be changed too in 1.21.6. - -

**Comment by DataM0del** [comment]
they're trying to abstract away the OpenGL part of rendering so they can see if porting to vulkan would be worth it.
also you forgot a `:` in the PR name lol

**Comment by MukjepScarlet** [comment]
I don't know any of them. The only thing I can do is to pray that someone will come to fix it.

**Comment by DataM0del** [comment]
> I don't know any of them. The only thing I can do is to pray that someone will come to fix it.

https://github.com/KosmoMoustache/shulkr use this to get a git repo for diffing Minecraft source, search up usages of e.g. RenderPhase and see what it's replaced with. I'll probably try to do that and see what I can do ~~(I tried it last day and it failed for some reason when it tried to decompile mc with CFR lol)~~ it was me using java 23 instead of 21

**Comment by MukjepScarlet** [comment]
You can create a repo or something for 1.21.4->1.21.5 changes. I don't want to download and run Gradle with Python... Unless I have time to migrate it into Gradle plugin or app.

**Comment by DataM0del** [comment]
> You can create a repo or something for 1.21.4->1.21.5 changes. I don't want to download and run Gradle with Python... Unless I have time to migrate it into Gradle plugin or app.

ok I guess, lol. time to get DMCA'd by Mojang (:skull:)
edit: https://github.com/DataM0del/mc-diffs

**Comment by DataM0del** [comment]
also draw context matrices is now a Matrix3x2fStack instead of a MatrixStack with Matrix4x4fStack

**Comment by MukjepScarlet** [comment]
> also draw context matrices is now a Matrix3x2fStack instead of a MatrixStack with Matrix4x4fStack

This is 1.21.5->1.21.6 change, not 1.21.4->1.21.5

File: src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/ClientInteropServer.kt [hunk 1]
```diff
@@ -46,15 +46,12 @@ object ClientInteropServer {
...
-            (15001..17000).random()
-        }
-    } catch (_: Exception) {
+    private var port = if (NetworkUtils.isPortAvailable(DEFAULT_PORT)) {
         logger.info("Default port $DEFAULT_PORT available.")
-
         DEFAULT_PORT
+    } else {
+        logger.info("Default port unavailable. Falling back to random port.")
+        (15001..17000).random()
```
Comment (DataM0del) [inline src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/ClientInteropServer.kt]: avoid depending on minecraft if possible, since they could change stuff at any time and it's not stable

**Comment by DataM0del** [comment]
> > also draw context matrices is now a Matrix3x2fStack instead of a MatrixStack with Matrix4x4fStack
> 
> This is 1.21.5->1.21.6 change, not 1.21.4->1.21.5

yes lol

File: src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/ClientInteropServer.kt (hunk 1 above)
Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/ClientInteropServer.kt]: This function is very stable, I viewed different versions

Comment (DataM0del) [reply src/main/kotlin/net/ccbluex/liquidbounce/integration/interop/ClientInteropServer.kt]: well then ok, but they could do what they did in 1.21.5 and just remove stuff that has existed for years and replace it with more abstractions or just remove it outright

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt [hunk 2]
```diff
@@ -142,7 +141,8 @@ inline fun renderEnvironmentForWorld(matrixStack: MatrixStack, draw: WorldRender
     val camera = mc.entityRenderDispatcher.camera ?: return
 
     GlStateManager._enableBlend()
-    RenderSystem.blendFunc(GlStateManager.SrcFactor.SRC_ALPHA, GlStateManager.DstFactor.ONE_MINUS_SRC_ALPHA)
+    // FIXME
+//    RenderSystem.blendFunc(GlStateManager.SrcFactor.SRC_ALPHA, GlStateManager.DstFactor.ONE_MINUS_SRC_ALPHA)
```
Comment (DataM0del) [inline src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: you need to use render pipelines to add blend functions and etc. idk if there's another way to do that lol

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt [hunk 3]
```diff
@@ -157,7 +157,8 @@ inline fun renderEnvironmentForWorld(matrixStack: MatrixStack, draw: WorldRender
 }
 
 inline fun renderEnvironmentForGUI(matrixStack: MatrixStack = MatrixStack(), draw: GUIRenderEnvironment.() -> Unit) {
-    GlStateManager._setShader(ShaderProgramKeys.POSITION_TEX_COLOR)
+    // FIXME
+//    GlStateManager._setShader(ShaderProgramKeys.POSITION_TEX_COLOR)
```
Comment (DataM0del) [inline src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: `VertexFormats.POSITION_TEX_COLOR` or something, I forgot. you need to use that via a render pipeline. idk what other way to do that than render pipelines right now

**Review by DataM0del — APPROVED** [review]

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt (hunk 2 above)
Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: idk the exact way to use it. If there's some examples that will be good

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt (hunk 3 above)
Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: ShaderProgramKeys is not needed I think. Because I found it's almost bound to one certain VertexFormat in 1.21.4 branch

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt (hunk 2 above)
Comment (DataM0del) [reply src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: idk right now either lol

Comment (DataM0del) [reply src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: https://github.com/DataM0del/mc-diffs/blob/c12982a76ed15210ab261c98bcf6ba725cdd3c0e/src/com/mojang/blaze3d/systems/RenderPass.java#L27
if you can get the render pass then you can set the current pipeline, idk if you need to reset it or anything.

File: src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt (hunk 3 above)
Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt]: This usage has no effect here. I removed it

**Comment by MukjepScarlet** [comment]
Remaining:
- Shader system, I don't know how to change. They are @1zun4 and @ccetl 's creations.
- Few mixins.
- MCEF.
- Verifying all changed features. e.g. FontRenderer, CustomAmbience, ItemImageAtlas cuz they are closely rewritten.

**Comment by MukjepScarlet** [comment]
And the render system. I don't know how to correctly setup RenderPipeline. Currently they don't render anything.

**Comment by VillainsRule** [comment]
> Remaining:
> 
> * Shader system, I don't know how to change. They are @1zun4 and @ccetl 's creations.
> * Few mixins.
> * MCEF.
> * Verifying all changed features. e.g. FontRenderer, CustomAmbience, ItemImageAtlas cuz they are closely rewritten.

Do you plan to do the last 3? Does mcef have a .5 version?

**Comment by MukjepScarlet** [comment]
I requested izuna to fix 1.21.5 MCEF. I will do very few other stuffs because I don't know most of them.

**Comment by VillainsRule** [comment]
> I requested izuna to fix 1.21.5 MCEF. I will do very few other stuffs because I don't know most of them.

mcef has a 1.21.5 branch?

https://github.com/CinemaMod/mcef/tree/1.21.5

https://github.com/CinemaMod/mcef/commit/adf0ace3bf873bc33ba5084b6944539470f97929

**Comment by MukjepScarlet** [comment]
Incompatible with @1zun4 's accelerated render.

**Comment by MukjepScarlet** [comment]
New custom ambience custom color
image
the font color is changed too...

File: src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/MixinPlayerInventory.java [hunk 4]
```diff
@@ -41,8 +41,10 @@ public class MixinPlayerInventory {
 
     /**
      * Override the original slot based on the server-side slot information.
+     *
+     * FIXME: where is getBlockBreakingSpeed?
```
Comment (DataM0del) [inline src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/MixinPlayerInventory.java]: it got moved into the PlayerEntity class:

https://github.com/DataM0del/mc-diffs/blob/ab72fa49dc42acc54493d7798130ed5127396d1a/src/net/minecraft/entity/player/PlayerEntity.java#L665-L690

**Review by DataM0del — APPROVED** [review]
getBlockBreakingSpeed was moved to the player entity class.

File: src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/MixinPlayerInventory.java (hunk 4 above)
Comment (MukjepScarlet) [reply src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/MixinPlayerInventory.java]: It uses `this.inventory.getSelectedStack()`

**Comment by DataM0del** [comment]
#7142

**Comment by MukjepScarlet** [comment]
@ccetl 
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2025-10-22 13:06:36
Description: Initializing game

java.lang.ExceptionInInitializerError
	at knot//net.minecraft.client.render.GameRenderer.handler$dbp000$liquidbounce$hookBlurEffectResize(GameRenderer.java:2551)
	at knot//net.minecraft.client.render.GameRenderer.onResized(GameRenderer.java)
	at knot//net.minecraft.client.MinecraftClient.onResolutionChanged(MinecraftClient.java:1490)
	at knot//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:730)
	at knot//net.minecraft.client.main.Main.main(Main.java:224)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.List.getLast(List.java:843)
	at knot//net.ccbluex.liquidbounce.common.GlobalFramebuffer.pop(GlobalFramebuffer.java:107)
	at knot//net.ccbluex.liquidbounce.render.buffer.Framebuffer.<init>(Framebuffer.kt:62)
	at knot//net.ccbluex.liquidbounce.render.engine.BlurEffectRenderer.<clinit>(BlurEffectRenderer.kt:67)
	... 9 more
```

**Comment by MukjepScarlet** [comment]
```java
        if (!readStack.isEmpty()) {
            readStack.removeLast();
            if (!minecraftChangesRead) {
                bindRead(readStack.getLast());
            }
        }
```
removeLast -> List.isEmpty
getLast -> Error

**Comment by MukjepScarlet** [comment]
I fixed this.

**Comment by MukjepScarlet** [comment]
@1zun4 MCEF issue now.

**Comment by superblaubeere27** [comment]
@MukjepScarlet ok, what is the problem?

**Comment by DataM0del** [comment]
> ok, what is the problem?

I keep crashing because of this error:

```
 java.lang.IllegalStateException: Texture does not exist, can't get change its filter before something initializes it
```

**Comment by DataM0del** [comment]
Ok, now it runs and stuff, but when I join a singleplayer world, it throws this exception:
```
java.lang.IllegalStateException: Close the existing render pass before performing additional commands
	at knot//net.minecraft.client.gl.GlResourceManager.writeToBuffer(GlResourceManager.java:172)
	at knot//net.minecraft.client.gl.GlBackend.createBuffer(GlBackend.java:146)
	at knot//com.mojang.blaze3d.vertex.VertexFormat.uploadImmediateVertexBuffer(VertexFormat.java:117)
	at knot//net.minecraft.client.render.RenderLayer$MultiPhase.draw(RenderLayer.java:1057)
	at knot//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:96)
	at knot//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:85)
	at knot//net.minecraft.client.render.VertexConsumerProvider$Immediate.drawCurrentLayer(VertexConsumerProvider.java:69)
	at knot//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:75)
        ... a few frames (DrawContext.`draw`, and 3 DrawContext.`drawItem`s)
	at knot//net.ccbluex.liquidbounce.render.ui.ItemFramebufferRenderer.render(ItemImageAtlas.kt:179)
	at knot//net.ccbluex.liquidbounce.render.ui.ItemImageAtlas.updateAtlas(ItemImageAtlas.kt:83)
	at knot//net.ccbluex.liquidbounce.render.engine.BlurEffectRenderer.startOverlayDrawing(BlurEffectRenderer.kt:107)
```

**Comment by DataM0del** [comment]
~~`(encoder as GlResourceManager).closePass()` should do the job, I put it after `encoder.clearColorTexture` in `ItemFramebufferRenderer#render(DrawContext)`~~ doesn't work? lol

**Comment by DataM0del** [comment]
OHH, it was because I put it in the wrong place, when I put it after `encoder.createRenderPass`, it crashed with a different exception:

```
 java.io.IOException: Bad PNG Signature
	at knot/net.minecraft.util.PngMetadata.validate(PngMetadata.java:50) ~[minecraft-merged-46a91e8ebd-1.21.5-net.fabricmc.yarn.1_21_5.1.21.5+build.1-v2.jar:?]
	at knot/net.minecraft.client.texture.NativeImage.read(NativeImage.java:157) ~[minecraft-merged-46a91e8ebd-1.21.5-net.fabricmc.yarn.1_21_5.1.21.5+build.1-v2.jar:?]
	at knot/net.minecraft.client.texture.NativeImage.read(NativeImage.java:120) ~[minecraft-merged-46a91e8ebd-1.21.5-net.fabricmc.yarn.1_21_5.1.21.5+build.1-v2.jar:?]
	at knot/net.ccbluex.liquidbounce.render.ui.ItemFramebufferRenderer.toNativeImage(ItemImageAtlas.kt:203) ~[main/:?]
	at knot/net.ccbluex.liquidbounce.render.ui.ItemImageAtlas.updateAtlas(ItemImageAtlas.kt:86) ~[main/:?]
	at knot/net.ccbluex.liquidbounce.render.engine.BlurEffectRenderer.startOverlayDrawing(BlurEffectRenderer.kt:107) ~[main/:?]
```

**Comment by DataM0del** [comment]
actually, no. `closeRenderPass` just nullifies whatever `encoder.createRenderPass` does.

**Comment by DataM0del** [comment]
The `toNativeImage` function seems to just pass a bunch of `0`s into `NativeImage.read`

**Comment by DataM0del** [comment]
Actually, that's because we read the data before the data is actually uploaded.

**Comment by DataM0del** [comment]
I did something I think... LOL (it froze, then a few minutes later went to a black screen with a cursor which didn't move, and then I had to force it to shut off)

https://files.catbox.moe/g5c09r.png

**Comment by MukjepScarlet** [comment]
Your image shows it drew successfully (but on screen, lol)

**Comment by MukjepScarlet** [comment]
We want the items to be drawn into the GpuTexture.

**Comment by DataM0del** [comment]
I basically did a fast fork bomb on the render tick, all I did, is that I just made `toNativeImage` use `suspend`, so it would wait for `dataUploadedCallback` before it tried to read it into a `NativeImage`. The problem is that I called it incorrectly in a non-suspend function by launching a coroutine scope in the IO context, so it would launch it a bunch of times.

**Comment by VillainsRule** [comment]
@MukjepScarlet so the client boots right? and it's just modules that need fixing...?

**Comment by MukjepScarlet** [comment]
- [x] Shaders need further refactoring/rewriting (broken now)
- [X] Resizing window -> GL error (maybe because of 1)
- [ ] Other mixin issues

**Comment by superblaubeere27** [comment]
I did a review of all render modules:
- [x] AntiBlind > Nausea does not work
- [x] Outline Modes:
  - ESP > Outline Mode causes the game to crash
  - ItemESP > Outline Mode crashes the game
- [x] ItemChams > causes the game to crash

everything else seems to function. Impressive work!

**Comment by MukjepScarlet** [comment]
- [ ] BlurEffectRenderer (for HUD) half broken, issue 1: enchanted item rendering, issue 2: alpha incorrect
- [x] CustomAmbience - CustomLightColor broken
- [ ] CustomAmbience - Fog - bg color broken
- [x] FontRenderer UTF8 (?)

File: src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/gl/MixinGlDebug.java [hunk 5]
```diff
@@ -32,10 +32,15 @@ private void injectAdvancedDebugInfo(Logger logger, String format, Object arg) {
...
+        locationText.append('?');
 
         if (finalElement != null) {
-            locationText = finalElement.getClassName() + "." + finalElement.getMethodName() + ":" + finalElement.getLineNumber();
+            locationText.append(finalElement.getClassName())
+                    .append('.')
+                    .append(finalElement.getMethodName())
+                    .append(':')
+                    .append(finalElement.getLineNumber());
         }
```
Comment (superblaubeere27) [inline src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/client/gl/MixinGlDebug.java:41]: This is not equivalent to the original code.

This now prints `(at ?ClassName.method:137)`.

**Comment by MukjepScarlet** [comment]
Who wanna test other features?

File: src/main/kotlin/net/ccbluex/liquidbounce/render/buffer/AbstractFramebuffer.kt [hunk 6]
```diff
@@ -53,7 +53,7 @@ abstract class AbstractFramebuffer: Closeable {
                 clearColor.a / 255.0F
             )
 
-            if (useDepth) {
+            if (!useDepth) {
                 glClearDepth(1.0)
             }
```
Comment (superblaubeere27) [inline src/main/kotlin/net/ccbluex/liquidbounce/render/buffer/AbstractFramebuffer.kt:58]: This is wrong. The depth buffer needs to be cleared before the frame so that the old depth image does not interfere with the generation of the new image.

So it has to be cleared if there is a depth buffer. If there is no depth buffer, there is no sense in clearing it or it might even cause errors, hence the if.

Please revert this commit.

File: src/main/kotlin/net/ccbluex/liquidbounce/additions/FramebufferAddition.kt [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+import com.mojang.blaze3d.textures.GpuTexture
+import net.minecraft.client.gl.Framebuffer
+
+interface FramebufferAddition {
+
+    fun `liquidbounce$setColorAttachment`(texture: GpuTexture?): GpuTexture?
+
+    fun `liquidbounce$setDepthAttachment`(texture: GpuTexture?): GpuTexture?
+
+}
```
Comment (superblaubeere27) [inline src/main/kotlin/net/ccbluex/liquidbounce/additions/FramebufferAddition.kt:32]: What is this used for?

Comment (MukjepScarlet) [reply src/main/kotlin/net/ccbluex/liquidbounce/additions/FramebufferAddition.kt:32]: I was tried to make blur correct on Mac but failed
If it's useless u can remove it before final merging.

**Comment by DataM0del** [comment]
1.21.11+ will force you to use M*jmap, since Yarn won't update for those versions because the client is no longer name remapped.

**Comment by MukjepScarlet** [comment]
I know. At least we should go to 1.21.10 at first. I'm waiting @1zun4 to do the rest job of this PR, then I can start 1.21.6. If no big render rewriting, I can finish in 1 week.

**Comment by VillainsRule** [comment]
> I know. At least we should go to 1.21.10 at first. I'm waiting @1zun4 to do the rest job of this PR, then I can start 1.21.6. If no big render rewriting, I can finish in 1 week.

what still needs to be done functionally?

**Comment by MukjepScarlet** [comment]
> what still needs to be done functionally?

See TODOs. Blur is skipped on OSX.

**Comment by VillainsRule** [comment]
> > what still needs to be done functionally?
> 
> See TODOs. Blur is skipped on OSX.

i'm sorry i don't speak english so i can't read the todo, can you summarize in my language?

**Comment by MukjepScarlet** [comment]
I don't know Russian. And why don't use AI

**Comment by umbrageodotus** [comment]
> 1.21.11+ will force you to use M*jmap, since Yarn won't update for those versions because the client is no longer name remapped.

Why not Parchment? It has javadocs... also, mojmap is good... :'(

**Comment by DataM0del** [comment]
> > 1.21.11+ will force you to use M*jmap, since Yarn won't update for those versions because the client is no longer name remapped.
> 
> Why not Parchment? It has javadocs... also, mojmap is good... :'(

mojmap is really garbage, `ResourceLocation` is very verbose compared to `Identifier`, or `ServerboundPlayerInputPacket`... yuck.

**Comment by umbrageodotus** [comment]
Disagree.

**Comment by DataM0del** [comment]
in the end it's all just opinions, so leave it there I guess...

**Comment by VillainsRule** [comment]
@MukjepScarlet <3 thanks for all of the work on this!

**Comment by sqlerrorthing** [comment]
❤️

**Comment by superblaubeere27** [comment]
Nice, great work 👍🏻
